# Site settings
# in the templates available like {{ site.myvariable }}.
title: Rammon Maintenance and Painting Contractors.
email: email needed 
brand: Ramor Maintenance
headline: Home Maintenance and Painting Contractors.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Ramor Maintenance and Painting Contractors. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: 0863710198

# Tracking


